[package]
name = "crabfetch"
version = "0.1.1"
authors = ["Livaco"]
edition = "2021"
description = "A fetch tool designed to be highly configurable while performant."
readme = "README.md"
repository = "https://github.com/LivacoNew/CrabFetch"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
shellexpand = "2.1.0"
colored = "2.1.0"
config = "0.14.0"
serde = "1.0.197"
serde_json = "1.0.114"
lazy_static = "1.4.0"
sqlite = "0.34.0"
libc = "0.2.153"
