# The modules to display
# Accepts; hostname, cpu, memory
modules = [
    "hostname",
    "underline",
    "os",
    "uptime",
    "cpu",
    "memory"
]


# Title seperator character
# E.g " > " puts "Processor > info"
seperator = " > "

# Title color
# Can be; black, red, green, yellow, blue, magenta, cyan, white
# All of these can be prefixed with "bright_" to be lighter versions, e.g bright_red
title_color = "bright_magenta"
# Whether to bold/italic the title
title_bold = true
title_italic = true

# How many decimal places to use on float values
decimal_places = 2


#
# Ascii
#

# If to even bother with the ASCII?
ascii_display = true

# The colors to render the ASCII in
# This array can be as long as the actual ASCII. Each entry represents the color at a certain %
# E.g ["red", "green"] would render the top half as red and the bottom half as green.
# ["yellow", "blue", "magenta"] would render 33.33% as yellow, then blue, than magenta.
ascii_colors = ["red", "blue", "red", "blue"]


#
# Hostname
#

# Title for Hostname
hostname_title = "Hostname"

# The format the CPU should be in. Placeholders;
# {hostname}            -> The hostname of the system.
# {username}            -> The username of the current user.
hostname_format = "{username}@{hostname}"


#
# Underline
#

# Length of the underline
underline_length = 24

# Whether to format the underline to the title formatting
underline_format = true



#
# CPU
#

# Title for CPU
cpu_title = "Processor"

# The format the CPU should be in. Placeholders;
# {name}                -> The name of the cpu.
# {core_count}          -> The number of cores.
# {thread_count}        -> The number of threads.
# {current_clock_mhz}   -> The current clock speed, in MHz.
# {current_clock_ghz}   -> The current clock speed, in GHz.
# {max_clock_mhz}       -> The maximum clock speed, in MHz.
# {max_clock_ghz}       -> The maximum clock speed, in GHz.
cpu_format = "{name} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"


#
# Memory
#

# Title for Memory
memory_title = "Memory"

# The format the memory should be in. Placehodlers;
# {phys_used_kib}       -> The currently used memory in KiB.
# {phys_used_mib}       -> The currently used memory in MiB.
# {phys_used_gib}       -> The currently used memory in GiB.
# {phys_max_kib}        -> The maximum total memory in KiB.
# {phys_max_mib}        -> The maximum total memory in MiB.
# {phys_max_gib}        -> The maximum total memory in GiB.
# {percent}             -> Percentage of memory used
memory_format = "{phys_used_gib} GiB / {phys_max_gib} GiB ({percent}%)"


#
# OS
#

# Title for OS
os_title = "Operating System"

# The format the OS should be in. Placehodlers;
# {distro}              -> The distro name
# {kernel}              -> The kernel version
os_format = "{distro} ({kernel})"


#
# Uptime
#

# Title for uptime
uptime_title = "System Uptime"

# The format the uptime should be in. Placehodlers;
# {hours}               -> The hours
# {minutes}             -> The minutes
# {seconds}             -> The seconds
#
# NOTE: These are expected to be used in order. E.g Using only {seconds} will not give you the proper system uptime
uptime_format = "{hours}h {minutes}m {seconds}s"
