# For more in-depth configuration docs, please view https://github.com/LivacoNew/CrabFetch/wiki


# The modules to display and in what order.
# All modules; space, underline:{length}, segment:{name}, end_segment, hostname, cpu, gpu, memory, swap, mounts, host, displays, os, packages, desktop, terminal, shell, battery, uptime, locale, editor, colors, bright_colors
modules = [
    "hostname",
    "underline:16",

    "cpu",
    "gpu",
    "memory",
    "swap",
    "mounts",
    "host",
    "displays",

    "os",
    "packages",
    "desktop",
    "terminal",
    "shell",
    "editor",
    "uptime",
    "locale",
    "music",
    "initsys",
    "processes",

    "space",
    "colors",
    "bright_colors"
]

# Whether to treat unknown modules as a raw text output, allowing you to use custom strings n stuff.
# Yes, these support color placeholders.
unknown_as_text = false

# The default separator between a modules title and it's value
separator = " > "
# The default color of a modules title
# Can be; black, red, green, yellow, blue, magenta, cyan, white
# All of these can be prefixed with "bright_" to be lighter versions, e.g bright_red
title_color = "bright_magenta"
# Whether to bold/italic the title by default too
title_bold = false
title_italic = false

# The default decimal places to provide in a module
decimal_places = 2

# Whether to have all module values as inline, e.g; https://i.imgur.com/UNyq2zj.png
# To add padding use the "separator" and add some spaces
inline_values = false

# The character to use in the underline module
underline_character = '―'

# The character for each color in the colors module
color_character = "   "
# Margin between each character
color_margin = 0
# And if to set the color to the background instead of on the character
color_use_background = true

# Format of segments
# Segments can be defined in the modules array
segment_top = "{color-white}[======------{color-brightmagenta} {name} {color-white}------======]"
segment_bottom = "{color-white}[======------{color-brightmagenta} {name_sized_gap} {color-white}------======]"

# Formatting characters used in progress bars 
progress_left_border = '['
progress_right_border = ']'
progress_progress = '='
progress_empty = ' '
# The target length of the progress bar
progress_target_length = 20

# Whether to use 'ibibytes opposed to 'gabytes 
# E.g use Gibibytes (GiB) opposed to Gigabytes (GB)
use_ibis = false

# Whether to use known checksums to attempt to find the version of some stuff e.g terminal/shell/editor
# Disabled by default as it was seen as "too cheaty"
# If your benchmarking, disable it as well. If your a end user, you likely won't care if it's on or not.
use_version_checksums = false

# Whether to supress any errors that come or not
suppress_errors = true

# Percentage coloring thresholds 
# Empty this section to make it not color 
# Values are in the format of "{percentage}:{color}"
percentage_color_thresholds = [
    "75:brightgreen",
    "85:brightyellow",
    "90:brightred"
]


[ascii]
# If to display the ASCII distro art or not
display = true

# The colors to render the ASCII in
# This array can be as long as the actual ASCII. Each entry represents the color at a certain %
# E.g ["red", "green"] would render the top half as red and the bottom half as green.
# ["yellow", "blue", "magenta"] would render 33.33% as yellow, then blue, than magenta.
colors = ["bright_magenta"]

# The amount of space to put between the ASCII and the info
margin = 4




# Below here is the actual modules
# Refer to the wiki for any module-specific parameters or hidden parameters
# Also remember that you can override some stuff on these, e.g the title formatting. Again check the wiki.

[hostname]
title = ""
# Placeholders;
# {hostname} -> The hostname
# {username} -> The username of the current user
format = "{color-brightmagenta}{username}{color-white}@{color-brightmagenta}{hostname}"


[cpu]
title = "CPU"
# Placeholders;
# {name} -> The name of the cpu.
# {core_count} -> The number of cores.
# {thread_count} -> The number of threads.
# {current_clock_mhz} -> The current clock speed, in MHz.
# {current_clock_ghz} -> The current clock speed, in GHz.
# {max_clock_mhz} -> The maximum clock speed, in MHz.
# {max_clock_ghz} -> The maximum clock speed, in GHz.
# {arch} -> The architecture of your CPU.
format = "{name} {arch} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"


[gpu]
# Whether to try to search a separate AMD specific file to try to improve accuracy on AMD GPU's 
amd_accuracy = true

# Ignore any GPU's that are marked as "disabled" by Linux
ignore_disabled_gpus = true


# Placeholders;
# - {index} -> The index of the GPU, only useful if you have more than one GPU.
title = "GPU"
# Placeholders;
# {vendor} -> The vendor of the GPU, e.g AMD
# {model} -> The model of the GPU, e.g Radeon RX 7800XT
# {vram} -> The total memory of the GPU.
format = "{vendor} {model} ({vram})"


[memory]
title = "Memory"
# Placeholders;
# {used} -> The currently in-use memory.
# {max} -> The maximum total memory.
# {bar} -> A progress bar representing the total space available/taken.
# {percent} -> Percentage of memory used
format = "{used} / {max} ({percent})"


[swap]
title = "Swap"
# Placeholders;
# {used} -> The currently used swap.
# {max} -> The maximum total swap.
# {bar} -> A progress bar representing the total space available/taken.
# {percent} -> Percentage of swap used
format = "{used} / {total} ({percent})"


[mounts]
# Each mount has it's own entry. Title Placeholders;
# {device} -> Device, e.g /dev/sda
# {mount} -> The mount point, e.g /home
# {filesystem} -> The filesystem running on that mount.
title = "Disk ({mount})"

# Placeholders;
# {device} -> Device, e.g /dev/sda
# {mount} -> The mount point, e.g /home
# {space_used} -> The space used.
# {space_avail} -> The space available.
# {space_total} -> The total space.
# {filesystem} -> The filesystem running on that mount.
# {bar} -> A progress bar representing the total space available/taken.
# {percent} -> The percentage of the disk used.
format = "{space_used} used of {space_total} ({percent}) [{filesystem}]"

# A ignore list for any point points OR filesystems to ignore
# The entries only need to start with these to be ignored
ignore = [
    # Filesystems
    "tmpfs", 
    "fuse", 
    "binfmt", 
    "configfs", 
    "debugfs", 
    "mqueue", 
    "tracefs", 
    "hugetlbfs", 
    "bpf", 
    "pstore", 
    "cgroup", 
    "dev", 
    "securityfs", 
    "autofs", 
    "efivar", 
    "sys", 
    "proc", 
    "swap", 
    "ramfs", 

    # Mounts
    "/boot/",     # Boot partition 
    "/snap/",     # Snap
    # Android-Specific Ignored Mounts
    # I have no idea what these do, they just seem to be irrelevant to my termux environment
    "/sys/",
    "/apex/",
    "/dev/",
    "/cache",
    "/data",
    "/product",
    "/prism",
    "/omr",
    "/odm",
    "/efs",
    "/optics",
    "/vendor",
    "/metadata",
    "/system"
]


[host]
title = "Host"
# Placeholders;
# {host} -> The name of the host, either a motherboard name or a laptop model
# {chassis} -> The chassis type, e.g Desktop or Laptop or whatever
format = "{host} ({chassis})"


[displays]
# Will make a new line per entry.
# Title Placeholders;
# {name} -> The monitor DRM name, e.g DP-2
# {make} -> The monitor's make
# {model} -> The monitor's model
title = "Display ({make} {model})"

# The format each display should be in. Placeholders;
# {make} -> The monitor's make
# {model} -> The monitor's model
# {name} -> The monitor DRM name, e.g DP-2
# {width} -> The monitor's width
# {height} -> The monitor's height
# {refresh_rate} -> The monitor's refresh rate. This won't work in x11!
format = "{width}x{height} @ {refresh_rate}Hz ({name})"

# Whether to scale the width/height according to the screen's scale. Only availabe on Wayland.
# This will output wrong with fractional scaling, as the library used to interact with Wayland doesn't support fractional scaling yet.
scale_size = false


[os]
title = "Operating System"
# Placeholders;
# {distro} -> The distro name
# {kernel} -> The kernel version
format = "{distro} ({kernel})"

# Display the kernel version on a newline and if so, what format to use 
# Only {kernel} is available in format.
newline_kernel = false
kernel_title = "Kernel"
kernel_format = "Linux {kernel}"


[packages]
title = "Packages"
# This format is for each entry, with all entries being combined into a single string separated by a comma. Placeholders;
# {manager} -> The name of the manager
# {count} -> The amount of packages that manager reports
format = "{count} ({manager})"

# List of package managers to ignore, for whatever reason you choose to
ignore = []


[desktop]
title = "Desktop"
# Placeholders;
# {desktop} -> The name of the desktop
# {display_type} -> The type of display server, aka x11 or wayland.
format = "{desktop} ({display_type})"


[terminal]
title = "Terminal"
# Placeholders;
# {name} -> The name of the terminal, e.g kitty
# {path} -> The path of the terminal, e.g /usr/bin/kitty
# {version} -> The version of the terminal
format = "{name} {version}"

# Whether to find the name of the current PTS if SSH is being used. This is a togglable option as most people probably won't care to go hunting for it.
chase_ssh_pts = false


[shell]
title = "Shell"
# Placeholders;
# {name} -> The name of the shell, e.g zsh
# {path} -> The path of the shell, e.g /usr/bin/zsh
# {version} -> The version of the shell.
format = "{name} {version}"

# Whether to show your default shell, instead of your current shell.
show_default_shell = false


[uptime]
title = "Uptime"


[editor]
title = "Editor"
# Placeholders;
# {name} -> The name of the editor
# {path} -> The path the editor is at
# {version} -> The version of the editor.
format = "{name} {version}"

# Whether to turn the name into a "fancy" variant. E.g "nvim" gets turned into "NeoVim"
fancy = true


[locale]
title = "Locale"
# Placeholders;
# {language} - The selected language
# {encoding} - The encoding selected, most likely UTF-8
format = "{language} ({encoding})"


[music]
title = "Music"
# Placeholders;
# {track} - The name of the track
# {album} - The name of the album
# {track_artists} - The names of all track artists
# {album_artists} - The names of all album artists
format = "{track} by {track_artists} ({album})"

# The player to get music data from
# The player must support the MPRIS standard (most do.)
# Known good selections; (make a GitHub issue if a known good one needs added here)
# - spotify
player = "spotify"


[battery]
# Placeholders;
# {index} -> The batterys index
title = "Battery {index}"

# Placeholders;
# {index} -> The batterys index
# {percentage} -> The battery percentage
# {bar} -> A progeress bar representing how full the battery is
format = "{percentage}%"


[initsys]
title = "Init System"


[processes]
title = "Total Processes"


[datetime]
title = "Date Time"
# Available placeholders; https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers
# CrabFetch wiki page coming soon for it instead (tm)
format = "%H:%M:%S on %e %B %G"



# You've reached the end! Congrats, have a muffin :)
