# vim:foldmethod=marker
# NOTE: This files designed to work with Vim folds!
# Apolgies if your using something else.

# General {{{
# The modules to display
# Accepts; hostname, cpu, memory
modules = [
    "hostname",
    "underline",
    "cpu",
    "gpu",
    "memory",
    "swap",
    "mounts",
    "host",

    "os",
    "packages",
    "desktop",
    "terminal",
    "shell",
    "uptime",
    "space",
    "colors",
    "bright_colors"
]


# Title seperator character
# E.g " > " puts "Processor > info"
seperator = " > "

# Title color
# Can be; black, red, green, yellow, blue, magenta, cyan, white
# All of these can be prefixed with "bright_" to be lighter versions, e.g bright_red
title_color = "bright_magenta"
# Whether to bold/italic the title
title_bold = true
title_italic = true

# How many decimal places to use on float values
decimal_places = 2

# }}}

# ASCII {{{

# If to even bother with the ASCII?
ascii_display = true

# The colors to render the ASCII in
# This array can be as long as the actual ASCII. Each entry represents the color at a certain %
# E.g ["red", "green"] would render the top half as red and the bottom half as green.
# ["yellow", "blue", "magenta"] would render 33.33% as yellow, then blue, than magenta.
ascii_colors = ["bright_magenta"]

# The amount of space to put between the ASCII and the info
ascii_margin = 4

# }}}
# Hostname {{{

# Title for Hostname
hostname_title = ""

# The format the CPU should be in. Placeholders;
# {hostname}            -> The hostname of the system.
# {username}            -> The username of the current user.
hostname_format = "{username}@{hostname}"

# Whether to color the hostname's placeholders the title color
# Mainly for if you remove the title and want to use it like a header, Neofetch style
hostname_color = true

# }}}
# Underline {{{

# Length of the underline
underline_length = 24

# Whether to format the underline to the title formatting
underline_format = true

# }}}
# CPU {{{

# Title for CPU
cpu_title = "Processor"

# The format the CPU should be in. Placeholders;
# {name}                -> The name of the cpu.
# {core_count}          -> The number of cores.
# {thread_count}        -> The number of threads.
# {current_clock_mhz}   -> The current clock speed, in MHz.
# {current_clock_ghz}   -> The current clock speed, in GHz.
# {max_clock_mhz}       -> The maximum clock speed, in MHz.
# {max_clock_ghz}       -> The maximum clock speed, in GHz.
cpu_format = "{name} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"

# }}}
# Memory {{{

# Title for Memory
memory_title = "Memory"

# The format the memory should be in. Placeholders;
# {phys_used_kib}       -> The currently used memory in KiB.
# {phys_used_mib}       -> The currently used memory in MiB.
# {phys_used_gib}       -> The currently used memory in GiB.
# {phys_max_kib}        -> The maximum total memory in KiB.
# {phys_max_mib}        -> The maximum total memory in MiB.
# {phys_max_gib}        -> The maximum total memory in GiB.
# {percent}             -> Percentage of memory used
memory_format = "{phys_used_gib} GiB / {phys_max_gib} GiB ({percent}%)"

#}}}
# Swap {{{

# Title for Swap
swap_title = "Swap"

# The format the swap should be in. Placeholders;
# {used_kib}       -> The currently used swap in KiB.
# {used_mib}       -> The currently used swap in MiB.
# {used_gib}       -> The currently used swap in GiB.
# {max_kib}        -> The maximum total swap  in KiB.
# {max_mib}        -> The maximum total swap in MiB.
# {max_gib}        -> The maximum total swap in GiB.
# {percent}             -> Percentage of swap used
swap_format = "{used_gib} GiB / {total_gib} GiB ({percent}%)"

#}}}
# GPU {{{

# Title for GPU
gpu_title = "GPU"

# The format the swap should be in. Placeholders;
# {vendor}             -> The vendor of the GPU, e.g AMD
# {model}              -> The model of the GPU, e.g Radeon RX 7800XT
# {vram_mb}            -> The total memory of the GPU in mb
# {vram_gb}            -> The total memory of the GPU in gb
gpu_format = "{vendor} {model} ({vram_gb} GB)"

#}}}
# OS {{{

# Title for OS
os_title = "Operating System"

# The format the OS should be in. Placeholders;
# {distro}              -> The distro name
# {kernel}              -> The kernel version
os_format = "{distro} ({kernel})"

# }}}
# Terminal {{{

# Title for Terminal
terminal_title = "Terminal"

# The format the Terminal should be in. Placeholders;
# {terminal_name}              -> The terminal name
terminal_format = "{terminal_name}"

# }}}
# Host {{{

# Title for Host
host_title = "Host"

# The format the Host should be in. Placeholders;
# {host}              -> The name of the host
host_format = "{host}"

# }}}
# Packages {{{

# Title for Packages
packages_title = "Packages"

# The format the Packages should be in. This format is simply for each entry, with all entries being combined into a single string seperated by a comma.
# Placeholders;
# {manager}              -> The name of the manager
# {count}                -> The amount of packages that manager reports
packages_format = "{count} ({manager})"

# }}}
# Uptime {{{

# Title for uptime
uptime_title = "System Uptime"

# The format the uptime should be in. Placeholders;
# {hours}               -> The hours
# {minutes}             -> The minutes
# {seconds}             -> The seconds
#
# NOTE: These are expected to be used in order. E.g Using only {seconds} will not give you the proper system uptime
uptime_format = "{hours}h {minutes}m {seconds}s"

# }}}
# Desktop {{{

# Title for desktop
desktop_title = "Desktop"

# The format the desktop should be in. Placeholders;
# {desktop}             -> The name of the desktop
# {display_type}        -> The type of display server, aka x11 or wayland.
desktop_format = "{desktop} ({display_type})"

# }}}
# Shell {{{

# Title for shell
shell_title = "Shell"

# The format the shell should be in. Placeholders;
# {shell}               -> The name of the shell, e.g zsh
# {path}                -> The path of the shell, e.g /bin/zsh
shell_format = "{shell}"

# }}}
# Mounts {{{

# Title for each mount. Placeholders;
# {device}              -> Device, e.g /dev/sda
# {mount}               -> The mount point, e.g /home
mount_title = "Disk {mount}"

# The format each mount should be in. Placeholders;
# {device}              -> Device, e.g /dev/sda
# {mount}               -> The mount point, e.g /home
# {space_used_mb}       -> The space used in megabytes.
# {space_avail_mb}      -> The space available in metabytes.
# {space_total_mb}      -> The total space in metabytes.
# {space_used_gb}       -> The space used in gigabytes.
# {space_avail_gb}      -> The space available in gigabytes.
# {space_total_gb}      -> The total space in gigabytes.
# {percent}             -> The percentage of the disk used.
mount_format = "{space_used_gb} GB used of {space_total_gb} GB @ ({percent}%)"

# Mounts that shouldn't be included
mount_ignored = ["/boot"]

# }}}
