# The modules to display and in what order.
# All modules; hostname, space, cpu, gpu, memory, swap, mounts, host, displays, os, packages, desktop, terminal, shell, uptime, colors, bright_colors
modules = [
    "hostname",

    "cpu",
    "gpu",
    "memory",
    "swap",
    "mounts",
    "host",
    "displays",

    "os",
    "packages",
    "desktop",
    "terminal",
    "shell",
    "uptime",

    "space",
    "colors",
    "bright_colors"
]

# The default seperator between a modules title and it's value
seperator = " > "
# The default color of a modules title
# Can be; black, red, green, yellow, blue, magenta, cyan, white
# All of these can be prefixed with "bright_" to be lighter versions, e.g bright_red
title_color = "bright_magenta"
# Whether to bold/italic the title by default too
title_bold = false
title_italic = false

# Whether to supress any errors that come or not
suppress_errors = true


[ascii]
# If to display the ASCII distro art or not
display = true

# The colors to render the ASCII in
# This array can be as long as the actual ASCII. Each entry represents the color at a certain %
# E.g ["red", "green"] would render the top half as red and the bottom half as green.
# ["yellow", "blue", "magenta"] would render 33.33% as yellow, then blue, than magenta.
colors = ["bright_magenta", "bright_magenta", "bright_blue", "bright_magenta", "bright_magenta"]

# The amount of space to put between the ASCII and the info
margin = 4




# Below here is the actual modules
# Refer to the wiki for any module-specific parameters or hidden parameters
# Also remember that you can override some stuff on these, e.g the title formatting.

[hostname]
title = ""
# Placeholders;
# {hostname} -> The hostname
# {username} -> The username of the current user
format = "{color-brightmagenta}{username}{color-white}@{color-brightmagenta}{hostname}"


[cpu]
title = "CPU"
# Placeholders;
# {name} -> The name of the cpu.
# {core_count} -> The number of cores.
# {thread_count} -> The number of threads.
# {current_clock_mhz} -> The current clock speed, in MHz.
# {current_clock_ghz} -> The current clock speed, in GHz.
# {max_clock_mhz} -> The maximum clock speed, in MHz.
# {max_clock_ghz} -> The maximum clock speed, in GHz.
format = "{name} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"


[gpu]
# The method for getting GPU info
# Getting accurate GPU info can be really slow. Because of this CrabFetch gives you two options
# - "pcisysfile" which searches the /sys/bus/pci/devices directory to find your GPU. This is fast but can be inaccurate due to decoding the vendor/product IDs
# - "glxinfo" which uses the glxinfo command to get the primary GPU. This is more accurate but REALLY slow!
# These methods may give be the exact same info, but if not you can swap to one or the other.
method = "pcisysfile"

# On top of the above, this allows you to choose to cache the GPU info.
# It's reccomended to use this with "glxinfo" to give you full speed while retaining accurate GPU info.
cache = false

title = "GPU"
# Placeholders;
# {vendor} -> The vendor of the GPU, e.g AMD
# {model} -> The model of the GPU, e.g Radeon RX 7800XT
# {vram_mb} -> The total memory of the GPU in mb
# {vram_gb} -> The total memory of the GPU in gb
format = "{vendor} {model} ({vram_gb} GB)"


[memory]
title = "Memory"
# Placeholders;
# {phys_used_kib} -> The currently used memory in KiB.
# {phys_used_mib} -> The currently used memory in MiB.
# {phys_used_gib} -> The currently used memory in GiB.
# {phys_max_kib} -> The maximum total memory in KiB.
# {phys_max_mib} -> The maximum total memory in MiB.
# {phys_max_gib} -> The maximum total memory in GiB.
# {percent} -> Percentage of memory used
format = "{phys_used_gib} GiB / {phys_max_gib} GiB ({percent}%)"


[swap]
title = "Swap"
# Placeholders;
# {used_kib} -> The currently used swap in KiB.
# {used_mib} -> The currently used swap in MiB.
# {used_gib} -> The currently used swap in GiB.
# {max_kib} -> The maximum total swap  in KiB.
# {max_mib} -> The maximum total swap in MiB.
# {max_gib} -> The maximum total swap in GiB.
# {percent} -> Percentage of swap used
format = "{used_gib} GiB / {total_gib} GiB ({percent}%)"


[mounts]
# Each mount has it's own entry. Title Placeholders;
# {device}              -> Device, e.g /dev/sda
# {mount}               -> The mount point, e.g /home
title = "Disk {mount}"

# Placeholders;
# {device} -> Device, e.g /dev/sda
# {mount} -> The mount point, e.g /home
# {space_used_mb} -> The space used in megabytes.
# {space_avail_mb} -> The space available in metabytes.
# {space_total_mb} -> The total space in metabytes.
# {space_used_gb} -> The space used in gigabytes.
# {space_avail_gb} -> The space available in gigabytes.
# {space_total_gb} -> The total space in gigabytes.
# {percent} -> The percentage of the disk used.
format = "{space_used_gb} GB used of {space_total_gb} GB ({percent}%)"

# Mounts that shouldn't be included
# The mounts only need to start with these
ignore = ["/boot", "/snap"]


[host]
title = "Host"


[displays]
# Same as mounts. Placeholders;
# {name} -> The monitor name, e.g eDP-2
title = "Display {name}"

# The format each display should be in. Placeholders;
# {name} -> The monitor name, e.g eDP-2
# {width} -> The monitor's width
# {height} -> The monitor's height
# {refresh_rate} -> The monitor's refresh rate
format = "{width}x{height} @ {refresh_rate}Hz"


[os]
title = "Operating System"
# Placeholders;
# {distro} -> The distro name
# {kernel} -> The kernel version
format = "{distro} ({kernel})"


[packages]
title = "Packages"
# This format is for each entry, with all entries being combined into a single string seperated by a comma. Placeholders;
# {manager} -> The name of the manager
# {count} -> The amount of packages that manager reports
format = "{count} ({manager})"


[desktop]
title = "Desktop"
# Placeholders;
# {desktop} -> The name of the desktop
# {display_type} -> The type of display server, aka x11 or wayland.
format = "{desktop} ({display_type})"


[terminal]
title = "Terminal"


[shell]
title = "Shell"
# Placeholders;
# {shell} -> The name of the shell, e.g zsh
# {path} -> The path of the shell, e.g /bin/zsh
format = "{shell} ({path})"


[uptime]
title = "Uptime"
# Placeholders;
# {hours} -> The hours
# {minutes} -> The minutes
# {seconds} -> The seconds
# NOTE: These are expected to be used in order. E.g Using only {seconds} will not give you the proper system uptime
format = "{hours}h {minutes}m {seconds}s"




# You've reached the end! Congrats, have a muffin :)
