#
# Processor
#

# Enables displaying the CPU
# Accepts true / false
enable_cpu = true

# The format the CPU should be in. Placeholders;
# {name}                -> The name of the cpu.
# {core_count}          -> The number of cores.
# {thread_count}        -> The number of threads.
# {current_clock_mhz}   -> The current clock speed, in MHz.
# {current_clock_ghz}   -> The current clock speed, in GHz.
# {max_clock_ghz}       -> The maximum clock speed, in GHz.
# {max_clock_mhz}       -> The maximum clock speed, in MHz.
cpu_format = "Processor > {name} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"


#
# Memory
#

# Enables displaying memory
# Accepts true/false
enable_memory = true

# The format the memory should be in. Placehodlers;
# {phys_used_kib} -> The currently used memory in KiB.
# {phys_used_mib} -> The currently used memory in MiB.
# {phys_used_gib} -> The currently used memory in GiB.
# {phys_max_kib} -> The maximum total memory in KiB.
# {phys_max_mib} -> The maximum total memory in MiB.
# {phys_max_gib} -> The maximum total memory in GiB.
memory_format = "Memory -> {phys_used_gib}GiB / {phys_max_gib}GiB"

