# The modules to display
# Accepts; cpu, memory
modules = [
    "cpu",
    "memory"
]


# Title seperator character
# E.g " > " puts "Processor > info"
seperator = " > "

# Title color
# Can be; black, red, green, yellow, blue, magenta, cyan, white
# All of these can be prefixed with "bright_" to be lighter versions, e.g bright_red
title_color = "magenta"
# Whether to bold/italic the title
title_bold = true
title_italic = true



#
# CPU
#

# Title for CPU
cpu_title = "Processor"

# The format the CPU should be in. Placeholders;
# {name}                -> The name of the cpu.
# {core_count}          -> The number of cores.
# {thread_count}        -> The number of threads.
# {current_clock_mhz}   -> The current clock speed, in MHz.
# {current_clock_ghz}   -> The current clock speed, in GHz.
# {max_clock_ghz}       -> The maximum clock speed, in GHz.
# {max_clock_mhz}       -> The maximum clock speed, in MHz.
cpu_format = "{name} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"


#
# Memory
#

# Title for Memory
memory_title = "Memory"

# The format the memory should be in. Placehodlers;
# {phys_used_kib} -> The currently used memory in KiB.
# {phys_used_mib} -> The currently used memory in MiB.
# {phys_used_gib} -> The currently used memory in GiB.
# {phys_max_kib} -> The maximum total memory in KiB.
# {phys_max_mib} -> The maximum total memory in MiB.
# {phys_max_gib} -> The maximum total memory in GiB.
memory_format = "{phys_used_gib}GiB / {phys_max_gib}GiB"
