# The modules to include and in what order.
modules = [
    "hostname",
    "underline",

    "cpu",
    "gpu",
    "memory",
    "swap",
    "mounts",

    "os",
    "desktop",
    "shell",
    "uptime"
]

# The module title seperator, e.g Processor {seperator} Blah Blah
title_seperator = ">"
# The title formatting
title_color = "bright_magenta"
title_bold = true
title_italic = true

# The number of decimal places to default to
decimal_places = 2

[ascii]
# Whether to display ASCII or not.
ascii = true
# The colors to render the ASCII in.
# This array can be as long as the actual ASCII. Each entry represents the color at a certain %
# E.g ["red", "green"] would render the top half as red and the bottom half as green.
# ["yellow", "blue", "magenta"] would render 33.33% as yellow, then blue, then magenta.
colors = ["bright_magenta"]


[underline]
length = 24
format = "{underline}"


# All the actual modules
# You can override the general options in these, e.g the title seperator, decimal places, etc.

[cpu]
title = "Processor"
format = "{name} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"

[memory]
title = "Memory"
format = "{phys_used_gib} GiB / {phys_max_gib} GiB ({percent}%)"

[swap]
title = "Swap"
format = "{used_gib} GiB / {total_gib} GiB ({percent}%)"

[gpu]
title = "GPU"
format = "{vendor} {model} ({vram_gb} GB)"

[os]
title = "Operating System"
format = "{distro} ({kernel})"

[uptime]
title = "System Uptime"
format = "{hours}h {minutes}m {seconds}s"

[desktop]
title = "Desktop"
format = "{desktop}"

[shell]
title = "Shell"
format = "{shell}"

[mount]
title = "Disk {mount}"
format = "{space_used_gb} GB used of {space_total_gb} GB @ ({percent}%)"
