name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: LivacoNew/CrabFetch
          ref: master
          path: CrabFetch

      - name: cargo test
        uses: Swatinem/rust-cache@v2.7.3
        run: |
          cd CrabFetch
          cargo test
      - name: cargo run
        uses: Swatinem/rust-cache@v2.7.3
        run: |
          cd CrabFetch
          cargo run
