name: Test, Run & Clippy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          repository: LivacoNew/CrabFetch
          ref: master
          path: CrabFetch

      # Setup Rust & Cargo's Cache
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: CrabFetch
        
      # Any deps we need, currently only libdbus-1
      - name: Install Dependencies
        run: |
          sudo apt -y update
          sudo apt -y install libdbus-1-dev

      # Actually run what we want to run
      - name: cargo clippy
        run: |
          cd CrabFetch
          cargo clippy
      - name: cargo test
        run: |
          cd CrabFetch
          cargo test
      - name: cargo test (all features)
        run: |
          cd CrabFetch
          cargo test --all-features
      - name: cargo run
        run: |
          cd CrabFetch
          cargo run
